# Generated by Django 5.2.1 on 2025-05-30 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='parlour',
            name='image',
            field=models.ImageField(upload_to='parlour_images/'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('user_location', models.CharField(help_text='Enter your address for home service', max_length=255)),
                ('is_approved', models.BooleanField(default=False)),
                ('parlour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.parlour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
