# Generated by Django 5.2.1 on 2025-05-31 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0003_booking_rating_booking_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_app.service'),
        ),
        migrations.AddField(
            model_name='parlour',
            name='services',
            field=models.ManyToManyField(related_name='parlours', to='service_app.service'),
        ),
    ]
